topics:
  - name: keyboard
    topic: /hulk_keyboard/speed
    timeout: 0.5  
    priority: 200

  - name: trajectory
    topic: /hulk_trajectory/speed
    timeout: 0.5  
    priority: 100

  - name: zerospeed
    topic: /hulk_node/cmd_vel_zero
    timeout: 0.0
    priority: 1

locks:
  - name: 'emergency_stop'
    topic: '/stop'
    timeout:   0.0
    priority:  1000